### ISSUE TITLE
cannot deploy to Vercel - next-translate-routes plugin is probably missing from next.config.js

### ISSUE THREAD

**Issue by wangwailok** [hozana/next-translate-routes#13]
![image](https://user-images.githubusercontent.com/7417322/147599137-d5e6775a-086c-445c-a919-0c51938f103a.png)
![image](https://user-images.githubusercontent.com/7417322/147599152-758ca671-f143-4827-921b-7792b371bc54.png)
everything work just fine on my local machine with build and run, but it just doesn't work on Vercel's cloud

**Comment by wangwailok** [comment]
Duplicate of #6

**Comment by cvolant** [comment]
It should work with v1.7.0. It it does not, please reopen this issue.
