### ISSUE TITLE
Bug - translateUrl

### ISSUE THREAD

**Issue by Bast1onCZ** [hozana/next-translate-routes#17]
Hello,
I've found a bug when trying <Link> a catch-all route (https://nextjs.org/docs/routing/dynamic-routes#catch-all-routes).

For a page represented by file in next `/pages/destination/[...destinationSlugs]`, when trying to use `<Link href="/destination/europe" />`, I receive replaced link `/destination/[...destinationSlugs]?destinationSlugs=europe` instead of `/destination/europe`.

The only problem is when the `[...destinationSlugs]` variable should be replaced with only one level of slug. If there are more of them, it works OK (e.g. `/destination/europe/prague`).

Could you please have a look at it?

**Comment by cvolant** [comment]
@Bast1onCZ It should be fixed. Please tell me if you still experience this issue with 1.7.1.

**Comment by Bast1onCZ** [comment]
@cvolant I'm sorry, after updated to 1.7.1, I still experience the same issue as described above

**Comment by frederikvanhevel** [comment]
also experiencing the same issue

**Comment by Bast1onCZ** [comment]
Any updates on this, please? I've found out that this problem occurs only in client environment and therefore these errors are shown:
![image](https://user-images.githubusercontent.com/28895562/179031854-965307ce-a364-4937-a619-5ab74368e066.png)

**Comment by cvolant** [comment]
I will work on it next week.

**Comment by cvolant** [comment]
@Bast1onCZ Could you try 1.7.2? I think it fixes the issue this time, so I am closing this issue again. Please re-reopen it if you still have the problem.
