### ISSUE TITLE
_middleware.ts doesn't work on translated routes

### ISSUE THREAD

**Issue by michalpulpan** [hozana/next-translate-routes#19]
Hello, 

I really enjoy this library but I'm facing very weird behavior when using NextJS 12 _middleware.ts function.

Using `_middleware.ts` simple as:
```typescript
import type { NextFetchEvent, NextRequest } from 'next/server'

const middleware = (req: NextRequest, ev: NextFetchEvent) => {
  return new Response('Hello, world!')
}

export default middleware;
```

works when:
```
- /pages
----/my-page <-- no _routes.json
--------index.tsx
--------_middleware.ts
```
And shows "Hello, world!"

But when I add _routes.json, middleware stops working.
    
```
- /pages
----/my-page
--------index.tsx
--------_routes.json <-- makes middleware not executing
--------_middleware.ts
```

It's quite important for me. Thanks!

**Comment by NikolaCava** [comment]
I have a similar problem, _middleware.tsx only works when I visit the "original" version of the route, but not when I use the translated route.

**Comment by cvolant** [comment]
@michalpulpan, @NikolaCava, could you try with the last version of Next (12.2.3)? Next team reworked the middleware ([see this issue](https://github.com/vercel/next.js/issues/35566#issuecomment-1159116801)).

**Comment by NikolaCava** [comment]
> @michalpulpan, @NikolaCava, could you try with the last version of Next (12.2.3)? Next team reworked the middleware ([see this issue](https://github.com/vercel/next.js/issues/35566#issuecomment-1159116801)).

I did, still one problem... now getServerSideProps wont run when I change the language

**Comment by cvolant** [comment]
Hmm... It sounds more like a Next issue than a next-translate-routes issue... What do you think, @NikolaCava ?

**Comment by JamesHemery** [comment]
I think i've related issue. When I add a next 12.2 middleware (stable syntax), when a click on a Link the getStaticProps methods no longer work properly and _app pageProps is empty. All works perfectly when I reload the page.

**Comment by cvolant** [comment]
I reproduced the bug, and published the repro in [this branch](https://github.com/hozana/next-translate-routes/tree/repro/get-static-props-with-middleware-issue-19). As soon as a middleware is set up, getStaticProps fail for non default locales.

I looked into it but I did not find where it comes from yet.

**Comment by cvolant** [comment]
Some news: I investigated this bug further. It appears to be a Next issue.
I reported [the issue in the next repo here](https://github.com/vercel/next.js/issues/39531).

The problem occurs when a matcher is declared in the middleware config. So, as long as the issue is not solved, we have 2 annoying options:
- either stick with next@12.1 and the previous middleware synthax,
- or remove the matcher from middleware config, and handle the selection from within the middleware.

**Comment by mlake** [comment]
I've been upgrading from 12.1.x to 12.3.4 and I'm running into the issue with translated paths (using _routes.json or routesTree). I've got **articles.tsx** and **/en/blog** but when I go to the page, I see the network is requesting **_next/data/xxxxxxxx/en/blog.json** which returns empty json response for the pageProps {} and messes up my page.
Prior to that, it looks like the browser is also requesting **_next/data/xxxxxxxx/en/articles.json** which does indeed have the right data.

I'm already upgrade-weary...but I'm noticing they introduced a new option in next 13.1 _skipMiddlewareUrlNormalize_

Seemingly we can capture /_next/data requests in middleware??

<img width="696" alt="image" src="https://user-images.githubusercontent.com/764071/212465872-3e087e30-4427-4471-ad07-681a7cbf8461.png">

https://nextjs.org/docs/advanced-features/middleware

Is this helpful to you? I'm fumbling my way through it all..

**Comment by cvolant** [comment]
@mlake Sooo you have a `/pages/articles.tsx` page that you translate in 'en' to "blog"? 

With a `routes.json` like this? 

```json
{
  "articles": {
    "en": "blog",
    ...
  },
  ...
}
```

**Comment by mlake** [comment]
that's right. It's called "blog" now ✊  (don't worry, there are legitimate translations!)
Actually my setup was like the following:

<img width="457" alt="image" src="https://user-images.githubusercontent.com/764071/212496735-d7ad67ad-362d-4198-8420-481ab386278b.png">

I forgot to note however, that I had followed nextjs' guide for setting up language detection by using an extra "default" locale in my configuration (you're supposed to turn off detection in the config, then use a middleware to do it server-side)

<img width="268" alt="image" src="https://user-images.githubusercontent.com/764071/212496973-a7b1fb9a-662d-4803-ae53-cc4f1010829f.png">

Today I've been experimenting with next 13.1 and trying to workaround using  _skipMiddlewareUrlNormalize_ to rewrite those .json requests to something that returns a response.

Probably this is doing something stupid, but I thought I'd share with you anyway:

```typescript

import {setNtrData} from "next-translate-routes/react/ntrData";
import {urlToFileUrl, fileUrlToUrl} from "next-translate-routes";

const routesTree = require("./routesTree.json")

const MATCHER = /^(?<prefix>\/_next\/data\/.*?\/)(?<locale>.*?)(?<path>\/.*)\.json/

export const middleware = (req: NextRequest) => {

    // seems that _next/data requests don't come here unless you use next 13.1

    if (MATCHER.test(req.nextUrl.pathname)) {
        const result = MATCHER.exec(req.nextUrl.pathname)

        if (result?.groups?.prefix && result?.groups?.locale && result?.groups?.path){

            //console.log("prefix: " + result?.groups?.prefix)
            //console.log("locale: " + result?.groups?.locale)
            //console.log("path: " + result?.groups?.path)
            const ntrData = {
                defaultLocale: "default",
                locales: ["default", "en", "fr"],
                routesTree,
                debug: true
            }
            setNtrData(ntrData)
            const url = req.nextUrl.clone()

            url.pathname = result.groups.path
            const fileUrl = urlToFileUrl(url, result.groups.locale)

            if (!fileUrl) throw Error("fileUrl not found!")

            //console.log("fileUrl.pathname: " + fileUrl.pathname)
            url.pathname = fileUrl.pathname

            // console.log(url)

            const defaultUrlTranslated = fileUrlToUrl(
                fileUrl.pathname + url.search
            , "default")

            //console.log("defaultUrlTranslated: " + defaultUrlTranslated)

            const rewriteUrlPath = `${result.groups.prefix}${result.groups.locale}${defaultUrlTranslated}.json`

            //console.log("rewriteUrlPath: " + rewriteUrlPath)

            url.pathname = rewriteUrlPath

            return NextResponse.rewrite(new URL(url, req.url))
        }
    }
    // ....there's more

}
```

does actually return correct .json responses...but since it's 13.1 there's some other errors "Failed to lookup route" or 404s for some xxxx.json.js files that haven't figured out yet.

Sensing I'll need to do a U-turn from next 13...unless there are more options I haven't tried:

<img width="273" alt="image" src="https://user-images.githubusercontent.com/764071/212498584-23cf6343-1ce2-4d31-9a61-44a4c8999532.png">


Thanks for any help!

**Comment by mlake** [comment]
Here's what I'm discovering with the following setup:
node: **18**
next: **12.2.3**
react: **17.0.2**
next-translate-routes: **1.9.1**

Using **_routes.json** in various spots
With some custom rewrites in **next.config.js**

If I use the following super-simple do-nothing middleware (no matchers or anything), there's no problem running locally (either dev or next build + next start)...BUT if I deploy this same middleware to Vercel, the pageProps are empty and I get client-side exception on my translated routes. frown emoji. sigh emoji.
without any middleware, the translated routes are fine.

```typescript
// middleware.ts

import {NextRequest, NextResponse} from "next/server"

export function middleware(request: NextRequest) {
    return
}


```

**Comment by vbrzezina** [comment]
> Here's what I'm discovering with the following setup: node: **18** next: **12.2.3** react: **17.0.2** next-translate-routes: **1.9.1**
> 
> Using **_routes.json** in various spots With some custom rewrites in **next.config.js**
> 
> If I use the following super-simple do-nothing middleware (no matchers or anything), there's no problem running locally (either dev or next build + next start)...BUT if I deploy this same middleware to Vercel, the pageProps are empty and I get client-side exception on my translated routes. frown emoji. sigh emoji. without any middleware, the translated routes are fine.
> 
> ```ts
> // middleware.ts
> 
> import {NextRequest, NextResponse} from "next/server"
> 
> export function middleware(request: NextRequest) {
>     return
> }
> ```

Got the same experience, when using any middleware the translations stop loading when navigationg through links (works after refresh)

**Comment by cvolant** [comment]
Yes, next-translate-routes does not support next@13 yet.

And if you really need a middleware, as concluded [here](https://github.com/hozana/next-translate-routes/issues/19#issuecomment-1212892652), you need either to downgrade next to 12.1 or remove the matcher. But according to @mlake , if you use Vercel, removing the matcher won't be enough... :confused:

__I invite all of you to upvote [this issue on nextjs repo](https://github.com/vercel/next.js/issues/39531) to help get this through.__

**Comment by cvolant** [comment]
The Next.js issue seems to be fixed from next@13.1.7.

**Comment by pinktonio** [comment]
> > Here's what I'm discovering with the following setup: node: **18** next: **12.2.3** react: **17.0.2** next-translate-routes: **1.9.1**
> > Using **_routes.json** in various spots With some custom rewrites in **next.config.js**
> > If I use the following super-simple do-nothing middleware (no matchers or anything), there's no problem running locally (either dev or next build + next start)...BUT if I deploy this same middleware to Vercel, the pageProps are empty and I get client-side exception on my translated routes. frown emoji. sigh emoji. without any middleware, the translated routes are fine.
> > ```ts
> > // middleware.ts
> > 
> > import {NextRequest, NextResponse} from "next/server"
> > 
> > export function middleware(request: NextRequest) {
> >     return
> > }
> > ```
> 
> Got the same experience, when using any middleware the translations stop loading when navigationg through links (works after refresh)

It's working fine in development. But when deploying to vercel I'm still getting the client-side exception in next@13.4.1 when navigating to a translated route via next links. Refreshes of the page do work, however.

**Comment by cvolant** [comment]
@pinktonio It looks like a Next issue again... Do you have the same issue with a redirected or rewritten page without next-translate-routes?
What do you have in the network tab of you browser dev tools? Are the prefetches requests and responses correct?

**Comment by pinktonio** [comment]
@cvolant No i don't have the same issue with a redirected or rewritten page without next-translate-routes. 
Yes the prefetch requests and responses seem fine and include the correctly translated path in the url.

**Comment by cvolant** [comment]
> the prefetch requests and responses seem fine and include the correctly translated path in the url

The prefetched requests should not be translated... Especially with the last next-translate-routes version. Could you provide a screenshot ? Or even a url ?

**Comment by pinktonio** [comment]
@cvolant You can check this url: https://leetdesk-qhelfyeu2-leetdesk.vercel.app/fr/actualites. The default language path is: https://leetdesk-qhelfyeu2-leetdesk.vercel.app/news
Try navigating to any item below "Dernières actus" or "Latest News" and you'll get redirected to the news item page with a client side exception. When reloading the page it works. And like i already mentioned this only happens on vercel and not in development.

**Comment by pinktonio** [comment]
@cvolant Have you gained any new insights on this?

**Comment by NSpehler** [comment]
@pinktonio Did you figure out a solution to this issue? I'm facing the same with Next.js 13.4.19 😞

**Comment by pinktonio** [comment]
> @pinktonio Did you figure out a solution to this issue? I'm facing the same with Next.js 13.4.19 😞

No unfortunately not. We are currently not using the translated routes until this gets solved.
