### ISSUE TITLE
Can someone add more documentation on routes.json ?

### ISSUE THREAD

**Issue by PrimozRome** [hozana/next-translate-routes#2]
I am having hard time understanding these and how to define route? Is there anyone that can help me?

2. Define your routes

In the pages folder, and in each of its subfolders, add a routes.json file with the following:

```
// `/pages/section/routes.json`
{
  "/": {
    "es": "seccion" // Folder path in es
  },
  "page1": {
    "default": "article", // Overwrite the default page path (fallback)
    "es": "articulo"
  },
  "page2": "definition", // Overwrite the page path for all language
}
```

The "/" section define the folder paths, each other section define the paths of a page file in this folder.

**Comment by cvolant** [comment]
There is no need to add a `routes.json` file if you don't want to customize the routes in this subfolder.
I updated the readme: I hope it is clearer now.

**Comment by cvolant** [comment]
Let me know if it is not clear enough: I can reopen this issue.
