### ISSUE TITLE
support for router.push

### ISSUE THREAD

**Issue by vana-dev** [hozana/next-translate-routes#23]
Hi, managing all links with "next-translate-routes / link" is very easy but in some cases I have to change routes through router.push which does not support translated route names. Any solution to this?

**Comment by wangwailok** [comment]
`import { translatePath } from "next-translate-routes/translateUrl";

useRouter().push(`${translatePath(`YOUR_PATH`, `YOUR_TARGET_LOCALE`)}`)

`

**Comment by wangwailok** [comment]
```
import { translatePath } from "next-translate-routes/translateUrl";

useRouter().push(${translatePath(YOUR_PATH, YOUR_TARGET_LOCALE)})
```
