### ISSUE TITLE
children is not assignable to <Link>

### ISSUE THREAD

**Issue by wangwailok** [hozana/next-translate-routes#26]
![image](https://user-images.githubusercontent.com/7417322/167836855-70def7cf-efdd-4837-b6d7-9a32a01c0b19.png)
![image](https://user-images.githubusercontent.com/7417322/167836929-36ae620d-1b16-47df-8d2a-e656b11cb82e.png)

**Comment by wangwailok** [comment]
My Next.js Version : 12.1.6

**Comment by jeromeheissler** [comment]
You can declare this in a .d.ts file : 
```typescript
declare module 'next-translate-routes/link' {
  export declare const Link: React.FC<React.PropsWithChildren<LinkProps>>;
  export default Link;
}
```

Or downgrade your project to React 17
