### ISSUE TITLE
URL path does not update when switching the language

### ISSUE THREAD

**Issue by samvdst** [hozana/next-translate-routes#27]
Steps to reproduce:
- Example repo: https://github.com/samvdst/next-translate-routes-test
- Navigate to: http://localhost:3000/de/hilfsorganisationen
- Switch to EN
- URL is "http://localhost:3000/hilfsorganisationen" instead of "http://localhost:3000/charities"
- After page refresh, the URL changes to http://localhost:3000/charities

**Comment by cvolant** [comment]
You can also change only one line in your code to make it work:
```js
function LanguageSwitcher() {
  const { pathname, query } = useRouter();
  const LANGS = ["en", "de"];
  return (
    <div>
      {LANGS.map((lang) => (
        <Link key={lang} href={{ pathname, query }} locale={lang}> // Here
          <a>{lang}</a>
        </Link>
      ))}
    </div>
  );
}
```
