### ISSUE TITLE
Next 12 crash

### ISSUE THREAD

**Issue by mcpll** [hozana/next-translate-routes#3]
Hi all,
i try to use your plugin with next 12.
But after update i received this error:

TypeError: Cannot read property 'push' of null
    at enhanceNextRouter (/node_modules/next-translate-routes/index.js:231:19)

**Comment by mxsotomayor** [comment]
Same issue here, on _app.tsx file, when wrapping with withTranslateRoutes.

**Comment by pilleck** [comment]
Hey, we have the same issue! :-)

**Comment by pilleck** [comment]
Hey @cvolant can you may take a look at this issue? Thank you in advance! 🙏

**Comment by cvolant** [comment]
@pilleck I will try to make it compatible with Next 12 by the end of the week.

**Comment by pilleck** [comment]
Thank you @cvolant! 😍

**Comment by cvolant** [comment]
Can you try the v1.5.5? I hope it solves you issue, but I am not sure since I cannot reproduce the bug you describe.
If it persists, could you post here a link to a repro so that I can investigate?

**Comment by pilleck** [comment]
Hey @cvolant it works very well! Thank you 👍
