### ISSUE TITLE
TranslatePath does not respect ignored segment

### ISSUE THREAD

**Issue by netdown** [hozana/next-translate-routes#34]
Hi,

I have the following route configuration in pages/landing/_routes.json:
`{
	"/": {
		"default": "."
	},
	"print": {
	  "hu": "foto",
	  "en": "prints"
	}
}`

I call translatePath like this:
`translatePath('landing/print')`

I would expect the function to return /foto (or /prints). However, it does return landing/foto. Note that the page urls are working fine, so my page loades at /foto and not at /landing/foto, the issue is only with the links.

**Comment by cvolant** [comment]
Thanks for the report. It is a bug, but waiting for it to be solved, you can try with `"/": "."` instead of `"/": { "default": "." }`.

**Comment by cvolant** [comment]
Ok, I tried to solve this bug, and did not reproduce it until I saw that you forgot `translatePath` second argument: the locale. You don't told it in what language you want to translate the path...
