### ISSUE TITLE
Setting ?queryparam when on root triggers refresh

### ISSUE THREAD

**Issue by draxx318** [hozana/next-translate-routes#35]
The problem occurs when trying to set a query param when on the root page on non-default locale only. Setting the query param should trigger a global component to render, instead, the page refreshes and render the component. For some reason, it requested a script that is wrong (see image).

![error](https://user-images.githubusercontent.com/30637513/181473094-a2ea9690-2670-45dd-8dd7-c1cefd344dae.png)

It's trying to access the it.js script where it is the locale in the url.

Im setting the Href of the Link component to '?queryparam=true'

**Comment by cvolant** [comment]
I cannot reproduce that bug. Could you make a minimal reproduction?
