### ISSUE TITLE
yarn install does not work on windows 

### ISSUE THREAD

**Issue by harrychy8** [hozana/next-translate-routes#39]
![image](https://user-images.githubusercontent.com/15678482/186037718-b0f9d686-b910-43eb-82f6-2b82e656c541.png)

When I run yarn install, it says that "rm" is not recognized. However, when I type it alone (bottom of the image), it works. Have anyone seen this before? Thank you very much for your help!

**Comment by cvolant** [comment]
Fixed with 1.9.0.
