### ISSUE TITLE
"No translate routes data found. next-translate-routes plugin is probably missing from next.config.js"

### ISSUE THREAD

**Issue by yzmp** [hozana/next-translate-routes#42]
I keep getting this error although I followed all the basic steps. I can even see the debug log in the terminal with all the redirects and rewrites created by the plugin, but somehow I'm still getting this error.

What I did:

1. Wrap you next config with the next-translate-routes plugin
```
// next.config.js
const { i18n } = require("./next-i18next.config");
const withTranslateRoutes = require("next-translate-routes/plugin")

module.exports = withTranslateRoutes({
  pageExtensions: ["page.tsx", "page.ts", "page.jsx", "page.js"],
  reactStrictMode: true,
  eslint: {
    ignoreDuringBuilds: true,
  },
  esModule: true,
  images: {
    domains: [
      //...
    ],
  },
  i18n,
  translateRoutes: {
    debug: true,
  },
});
```

2. Define your routes
```
// _routes.json
{
  "/": {
    "en": "hi",
    "es": "hola",
    "pt-BR": "oi"
  }
}
```

3. Wrap you \_app component with the withTranslateRoutes hoc
```
import { appWithTranslation } from "next-i18next";
import { wrapper } from "../redux";
import { withTranslateRoutes } from "next-translate-routes";

function MyApp({ Component, pageProps }: AppProps) {
  /**/
  return (
    <>
      <Component {...pageProps} />
    </>
  );
}

export default withTranslateRoutes(
  appWithTranslation(wrapper.withRedux(MyApp))
);
```

What I get in terminal:
```
[next-translate-routes] - Redirects: [
  {
    source: '/pt-BR/(hi|hola)/downloads/',
    destination: '/oi/downloads/',
    locale: false,
    permanent: false
  },
  {
    source: '/en/(oi|hola)/downloads/',
    destination: '/en/hi/downloads/',
    locale: false,
    permanent: false
  },
...
]
[next-translate-routes] - Rewrites: [
  {
    source: '/(oi|hi|hola)/downloads/',
    destination: '/downloads/'
  },
  {
    source: '/(oi|hi|hola)/about/',
    destination: '/about/'
  },
...
]
```
And eventually:
```
Error: [next-translate-routes] - No translate routes data found. next-translate-routes plugin is probably 
missing from next.config.js
    at withTranslateRoutes (\node_modules\next-translate-routes\react\withTranslateRoutes.js:63:15)
    at eval (webpack-internal:///./src/pages/_app.page.tsx:71:140)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I have searched for other issues here and in Google, but haven't find anything similar. What am I missing?

**Comment by simonhenke** [comment]
I had the same issue. After many unsuccessful tries to fix this, I installed v.1.7.2 instead of the latest release and now it's working fine. I'm on Nextjs version 11.1.2 with Preact 10.5.14.

**Comment by simonhenke** [comment]
Just upped the version incrementally and it seems like v. 1.8.0-1 is the latest version that still works for me.
So 1.8.0-2 seems to be the issue in my case, or the following commit:
https://github.com/hozana/next-translate-routes/commit/8bfee0f14f05e0b35e1e705711ff980e5e3e551d

any idea @cvolant ?

**Comment by cvolant** [comment]
Thank you both for reporting the issue. Having identified the precise version that introduced the bug is a great help. I will look at it as soon as I can.

**Comment by krystianjj** [comment]
Hi, I have the same issue, but my problem is little difference, because I use NX monorepo, and if I want to work next-translate in this monorepo I must add env variable `NEXT_TRANSLATE_PATH=apps/projectName` I think there is similar problem for me. Is there any variable where I can set up this? My error is `Error: [next-translate-routes] - No pages folder found.`

**Comment by cvolant** [comment]
Currently working on this issue...
@yzmp, @simonhenke, ...
1. Are you on Windows?
2. Could you give me the path to you `_app` file? Something like `/pages/_app.js`...

**Comment by cvolant** [comment]
@krystianjj your problem is different: what you are looking for is probably the `pageDirectory` config.
In `next.config.js`:
```
translateRoutes: {
  pageDirectory: 'apps/projetName',
}
```
See the [configuration section in the docs](https://github.com/hozana/next-translate-routes#configuration).

**Comment by krystianjj** [comment]
> @krystianjj your problem is different: what you are looking for is probably the `pageDirectory` config. In `next.config.js`:
> 
> ```
> translateRoutes: {
>   pageDirectory: 'apps/projetName',
> }
> ```
> 
> See the [configuration section in the docs](https://github.com/hozana/next-translate-routes#configuration).

@cvolant 
Unfortunately this did not solve the problem. 
I want to use your packege with this framework -> https://nx.dev/

**Comment by cvolant** [comment]
@yzmp I suspect that it comes from slashes in paths: `\` on Window and `/` on Linux.
I released next-translate-routes@1.9.0-3 yesterday, and it includes an attempt to fix this issue: could you try it and tell me if it works?

**Comment by simonhenke** [comment]
@cvolant I'm also on Windows and the path is `/pages/_app.page.tsx`.
I'm excited to try out the new version (probably tomorrow), I'll let you know if it helped :) Thanks!

**Comment by simonhenke** [comment]
@cvolant On 1.9.0-3, when I start the app, I now get the following error:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.readdirSync (fs.js:1038:10)
    at getAllRoutesFiles (C:\Users\...\node_modules\next-translate-routes\plugin\routesFiles.js:46:39)
```

**Comment by cvolant** [comment]
@simonhenke Could you try the latest version? next-translate-routes@1.9.1

**Comment by cvolant** [comment]
@simonhenke could you try the latest version? next-translate-routes@1.9.1

**Comment by simonhenke** [comment]
@cvolant I'm still getting the same error (`ERR_INVALID_ARG_TYPE`). In our project we currently have a branch on which we updated to Next12. I'll test the latest version of this lib there as well, maybe that works.

**Comment by simonhenke** [comment]
@cvolant Seems to work on Next12, nice! :)
