### ISSUE TITLE
translate-routes and language change

### ISSUE THREAD

**Issue by dsm-ostec** [hozana/next-translate-routes#44]
Hey there,

I'm using next-translate-routes and it works fine so far. But when I change the language, the paths were not redirected, but the site-content is correct.
My code for languageChange is like this:

```
function changeLanguage(language) {
    i18n
      .changeLanguage(language === 'EN' ? 'en' : 'de')
      .then((t) => {
        t('key');
      })
      .catch((err) => {
        console.log('something went wrong loading', err);
      });
    router.push({ pathname, query }, asPath, { locale: language });
  }
```

my i18 config:

```
i18n: {
    defaultLocale: 'en',
    locales: ['en', 'de'],
  },
```

and my _routes.json:
```
{
  "contact": {
    "en": "contact",
    "de": "kontakt"
  }
}
```

eg.:
I am on page /de/kontakt and use the languageSwitcher. The url changed to /kontakt. The component "contact" is correctly loaded and its translated content too. But the url is false. If I refresh the page in browser, the re-direrection to/contact is done correctly.

How can I change my changeLanguage-Function to make this work?

**Comment by dsm-ostec** [comment]
Hello again. Have a look at this sandbox-code: [Sandbox Language change translated routes](https://7b7st6.sse.codesandbox.io/news).
If you are on page /news  (englisch) an click to button "change to fr" url changes to "fr/news" instead of "fr/actualite" but the content of the page is rendered correct. After reload the url is correct.

EN: 
![image](https://user-images.githubusercontent.com/12607634/192958845-c780b987-9dd7-41fd-9b9d-6a909769bcf2.png)

After klick on button:
![image](https://user-images.githubusercontent.com/12607634/192959003-a9491382-5ca3-4f45-92fa-0dfdd6a87ca6.png)

**Comment by cvolant** [comment]
! I finally got it. It took me a while but here is the problem: you set the `as` prop to `asPath` in `router.push`. next-translate-routes lets you use a custom as prop if you want to: it means "I want to go there but then here is the url I want to display".

**Comment by Marko-Matijevic** [comment]
I have the same issue. First it shows original path and after refresh shows translated path. I am not sure how did you fix it with `as` prop could you elaborate more @cvolant? Thanks
