### ISSUE TITLE
Plugin can't be used with @sentry/nextjs

### ISSUE THREAD

**Issue by aleehedl** [hozana/next-translate-routes#48]
When using the [@sentry/nextjs plugin](https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/), the Sentry's HoC  `withSentryConfig` modifies the `_app.tsx`'s output quite a bit. The result is that `next-translate-router/plugin/loader.ts` fails while looking for the import of `next-translate-routes`.

Any ideas how to deal with this?

**Comment by cvolant** [comment]
Thanks for this report, @aleehedl, it will probably save me some time debugging, since we will setup this plugin in the coming weeks. I will look into it soon.

**Comment by cvolant** [comment]
@aleehedl I looked into it, struggled to understand what sentry was doing with their new proxyLoader, and finally found a simple solution: changing wrapping order. I added it [in the docs](https://github.com/hozana/next-translate-routes#with-sentrynextjs).
