### ISSUE TITLE
Can't install the latest version v1.9.0 with yarn

### ISSUE THREAD

**Issue by ViktorVojtek** [hozana/next-translate-routes#50]
Yarn throws the following errors and fail to add package.

https://registry.yarnpkg.com/@next/swc-android-arm64/-/swc-android-arm64-12.2.3.tgz: Request failed "502 Bad Gateway"
https://registry.yarnpkg.com/@next/swc-win32-arm64-msvc/-/swc-win32-arm64-msvc-12.2.3.tgz: Request failed "502 Bad Gateway"

Version 1.8.0 works fine.

**Comment by cvolant** [comment]
I can't reproduce it... It is surprising because next-translate-routes is not related to swc-android-arm64...
Can you provide a minimal reproduction?
