### ISSUE TITLE
Does this plugin support locale format en-US, es-MX, etc?

### ISSUE THREAD

**Issue by elliot619** [hozana/next-translate-routes#51]
So far I'm not able to make this plugin work in my app which has the locale configured in 5 characters as en-US, fr-CA, es-MX, etc.
Is this plugin intended with this format? Thanks

Here is my next.config.js i18n setup:

![image](https://user-images.githubusercontent.com/8999155/201194664-0bf65930-5df8-49c8-9e45-8e89c6ad15a5.png)

Here is how I have set up the _routes.json:

![image](https://user-images.githubusercontent.com/8999155/201194866-c0660a47-548c-406d-b248-9153875d7fd6.png)

**Comment by cvolant** [comment]
I tried with 5 characters locales, but everything worked fine.
Did you follow the [_how to_ section](https://github.com/hozana/next-translate-routes#how-to) in the docs? If yes, could you provide a minimal reproduction of you issue?

**Comment by cvolant** [comment]
Let me know if this issue should be reopened.
