### ISSUE TITLE
Update LinkProps to support Next.js 13 <Link> component

### ISSUE THREAD

**Issue by sdk1990** [hozana/next-translate-routes#62]
The current implementation doesn't fully support the latest update to the < Link > component. In previous versions we had to put an < a > as child in the < Link > component and add attributes such as "target" and "title" to it. Since some time this is not needed anymore, but this package doesn't support these attributes yet.

**Comment by mborecki** [comment]
@cvolant can you publish this code on npm?

**Comment by cvolant** [comment]
@mborecki Done.
