### ISSUE TITLE
Update pagesDirs to support Next.js 11 pages path

### ISSUE THREAD

**Issue by pqminh** [hozana/next-translate-routes#64]
https://github.com/hozana/next-translate-routes/blob/40baf73cb2a3785b542005f176d69ea5e11405d8/src/plugin/routesFiles.ts#L22

Error:  next-translate-routes does not support `/app` directory yet.

pagesDirs was undefined

Step reproduce
next@11.1.2
next-translate-routes@1.9.2

`var find_pages_dir = require('next/dist/lib/find-pages-dir');
var pages_dir = find_pages_dir.findPagesDir(process.cwd(), false);
console.log('pages_dir', pages_dir);`

`pages_dir` was string `{project}/pages`

**Comment by cvolant** [comment]
:open_mouth: 

Thank you for reporting.
So you mean that your code worked while routesFiles' code failed, despite you did exactly the same??

There is an other thing that surprise me: how is it possible that you get the ``next-translate-routes does not support `/app` directory yet.`` error if your `pagesDirs` is undefined? You should only see this error if `pagesDirs.appDir` is defined... Did you meant that `pagesDir` was undefined (while `pagesDirs` was defined)?
