### ISSUE TITLE
Routing does not work any more after update to next 13.3.0

### ISSUE THREAD

**Issue by dsm-ostec** [hozana/next-translate-routes#68]
Hey there,

I use the package and it worked great, but after update to next 13.3.0 the redirects doesn't seem to work anymore.

With debugging, I see a correct infos I think:

![image](https://user-images.githubusercontent.com/12607634/231749544-118f7c17-17cd-460b-8691-7e7466ddd5a8.png)

but when I click on a translated link I always get an 404. With non translated links the redirect works correct. 

Aftre I installed next version 13.2.4 again it works like a charm again.

Can you please have a look at this?

**Comment by cvolant** [comment]
I don't reproduce the issue... Can you first try next-translate-routes@1.10.1, then, if you still have the issue, tell be more about it? Logs, behavior, etc. If you can provide a minimal reproduction, that would help a lot.

**Comment by dsm-ostec** [comment]
I tried with next v13.3.0 and next-translate-routes@1.10.1. Nothing changed. I deleted yarn cache and my complete node-modules-folder but this doesn't change anything.

The redirects and rewrites I get in the log seems to be fine and the redirects still work. Just the rewrites are not working anymore.  If I write one of the rewrite-rules from the log directly in the next-config, this redirect works. I will try to create a sandbox for this issues to reproduce.

**Comment by dsm-ostec** [comment]
https://codesandbox.io/p/sandbox/affectionate-violet-422vgg?welcome=true

I created a sandbox-example. There the url "blog/:slug" is a translated path and should be reachable with /blog/test, /en/bloggy/test and /it/bloggo/test. 

But if you try, only the /blog/test oder /en/blog/test or /it/blog/test will lead to the page. The other urls will lead to 404.

**Comment by cvolant** [comment]
Interesting! Thanks for the reproduction @dsm-ostec!
I reproduce it only using `next dev`, not using `next build && next start`.
Using next@13.2.4, next-translate-routes@1.10.0 does not compile because of the `missing` property in redirects :disappointed:, but if I remove this prop, it works all good. So it seems to be a bug in next introduced with the 13.3.0. Maybe the same as [this issue](https://github.com/vercel/next.js/issues/48858).

**Comment by dsm-ostec** [comment]
Thank you for the quick help. Works great again. :)

**Comment by cvolant** [comment]
Yes, I used the workaround mentioned in [the aforementioned issue](https://github.com/vercel/next.js/issues/48858). Thanks you @jaapaurelio.
