### ISSUE TITLE
Add the ability to export the translations directly from the pages

### ISSUE THREAD

**Issue by Designer023** [hozana/next-translate-routes#69]
It would be really nice if instead of using `_routes.json` or `_routes.yaml` if we could export the translates routes directly from the page itself eg.

```
// about page

export const i18n = {
   routes: {
     fr: "à-propos",
     es: "acerca-de
    }
}
```

This would result in 2 pages for the `/fr/à-propos` and `/es/acerca-de` along side the original `/about` page.

P.S. Great work on this project 👍

**Comment by cvolant** [comment]
Yes, it could be handy... but, how would you translate a directory segment? I mean, consider the following pages directory:

```none
/pages/
 └ section/
     └ page.tsx
```

How would you translate the "section" segment in the url `/section/page`?
