### ISSUE TITLE
Mailto links are broken since v.1.9.2

### ISSUE THREAD

**Issue by simonhenke** [hozana/next-translate-routes#75]
Seems like some change in version 1.9.2 is causing the href of `mailto:`-links to be incorrectly parsed to `"/"`.

` <Link href="mailto:text@example.com">Contact</Link>`
is being rendered as
`<a href="/">Contact</a>`

Possible workarounds:
 - downgrade to v.1.9.1
 - in #55 I already mentioned a workaround for fixing incorrectly translated external links, which is to have a custom link component rendering either the link component from `next/link` or from `next-translate-routes/link` based on the href. This could be extended to also exclude `mailto:` hrefs like:
 `const Link = ["http","mailto:"].some(s => href.toString().startsWith(s)) ? NextLink : NextTranslateRoutesLink;`

**Comment by cvolant** [comment]
I fixed it in prerelease 1.11.0-0. I will release it in 1.11.0 soon.
