### ISSUE TITLE
How to use Next-translate-routes with Typescript

### ISSUE THREAD

**Issue by wangwailok** [hozana/next-translate-routes#8]
![Screenshot 2021-12-16 at 4 38 03 PM](https://user-images.githubusercontent.com/7417322/146336889-93c4ffa3-75ca-4a7c-bf63-0af1ebc2757c.png)

I have followed the sample on npm but the withTranslateRoutes function requires parameter of type 'ComponentType<AppProps>',
can anyone help?

**Comment by cvolant** [comment]
Thanks for the report. It should be fixed in the next release.

**Comment by wangwailok** [comment]
> 

Thank you very much!

**Comment by cvolant** [comment]
It should be fixed now. Please reopen this issue if you still have the problem from v1.7.0.
