### ISSUE TITLE
Redirection issue using getServerSideProps 

### ISSUE THREAD

**Issue by MaxTec** [hozana/next-translate-routes#82]
### Describe the bug
I've encountered a redirection issue when utilizing `getServerSideProps` on my project. The expected behavior is that visiting "/en/contact" would redirect to "/contact" since I have set the default language to English. However, the redirection fails to occur when `getServerSideProps` is utilized. When I remove `getServerSideProps`, the redirection works as expected.

### To Reproduce
1. Set up next-translate-routes with English as the default language.
2. Create a `/contact` page and implement `getServerSideProps`.
3. Visit "/en/contact" in the browser.
4. Observe that the redirection to "/contact" does not occur.

### System information
- OS: macOS
- Browser: chrome
- Version of Next.js: 13.3.1
- Version of next-translate-routes: 1.10.2

**Comment by cvolant** [comment]
Yes, you are right.
Unfortunately, this cannot be fixed using next-translate-route approach: trying to use a redirect would lead to a looping redirection.
The only way to do this seems to be using the middleware, as stated [here](https://github.com/vercel/next.js/discussions/18419#discussioncomment-1561577).
I will update next-translate-routes docs to mention it.

**Comment by cvolant** [comment]
Added to the docs [here](https://github.com/hozana/next-translate-routes#6-use-a-middleware-to-redirect-from-urls-with-the-default-locale-prefix).
